name: Deploy DotNet project to Azure Function App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: iana-win       # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: ⚙ func 4.x
      run: npm i -g azure-functions-core-tools@4 --unsafe-perm true  

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        include-prerelease: true

    - name: ⚙ dotnet 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet remove package Microsoft.NET.Sdk.Functions --version 3.0.13
        dotnet add package Microsoft.Azure.Functions.Worker --version 1.0.0
        dotnet add package Microsoft.Azure.Functions.Worker.Sdk --version 1.0.1
        dotnet add package Microsoft.Azure.Functions.Worker.Extensions.Http --version 3.0.12
        dotnet add package Microsoft.Azure.WebJobs.Extensions.Http --version 3.0.12        
        dotnet add package Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights --version 1.0.0-preview4
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
